### ISSUE TITLE
protectedApp = true开启加固时生成补丁文件出错(在Activity里面新添加成员变量时会出错)

### ISSUE THREAD

**Issue by xiaobaoCat** [TinkerPatch/tinkerpatch-flavors-sample#1]
org.jf.util.ExceptionWithContext: Class Lcom/tinkerpatch/flavors/MainActivity$4; has already been interned
	at org.jf.dexlib2.writer.builder.BuilderClassPool.internClass(BuilderClassPool.java:74)
	at org.jf.dexlib2.writer.builder.DexBuilder.internClassDef(DexBuilder.java:139)
	at com.tencent.tinker.build.decoder.DexDiffDecoder.generateChangedClassesDexFile(DexDiffDecoder.java:276)
	at com.tencent.tinker.build.decoder.DexDiffDecoder.onAllPatchesEnd(DexDiffDecoder.java:195)
	at com.tencent.tinker.build.decoder.ApkDecoder.patch(ApkDecoder.java:123)
	at com.tencent.tinker.build.patch.Runner.tinkerPatch(Runner.java:65)
	at com.tencent.tinker.build.patch.Runner.run(Runner.java:48)
	at com.tencent.tinker.build.patch.Runner.gradleRun(Runner.java:41)
	at com.tencent.tinker.build.patch.Runner$gradleRun.call(Unknown Source)
	at com.tencent.tinker.build.gradle.task.TinkerPatchSchemaTask.tinkerPatch(TinkerPatchSchemaTask.groovy:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)

**Comment by shwenzhang** [comment]
这个问题是tinker的一个问题，在1.7.10版本会修复

**Comment by simpleton** [comment]
您使用的是什么版本？1.1.6应该修复了这个问题
